FROM node:16-alpine as builder

WORKDIR /frontend

COPY ./package*.json ./ 


RUN npm install
ARG VUE_APP_BASE_URL
ENV VUE_APP_BASE_URL=${VUE_APP_BASE_URL}


ARG VUE_APP_EXAMPLE
ENV VUE_APP_EXAMPLE=$VUE_APP_EXAMPLE

COPY . . 

RUN npm run build

COPY . . 


# FROM nginx
# EXPOSE 2000
# COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
# COPY  /frontend/